wandb_version: 1

MAX_LENGTH:
  desc: null
  value: 512
HEAD_DROPOUT:
  desc: null
  value: 0.0
DATA_AUGMENTATION:
  desc: null
  value:
  - WR
FOLDS_NUM:
  desc: null
  value: 5
NUM_EPOCHS:
  desc: null
  value: 5
LEARNING_RATE:
  desc: null
  value: 2.0e-05
BATCH_SIZE:
  desc: null
  value: 16
FOLD_IDX:
  desc: null
  value: 0
LOSS_FN:
  desc: null
  value: cross_entropy
SEED:
  desc: null
  value: 5581
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.40.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1716734316
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 71
      3:
      - 16
      - 23
      4: 3.10.12
      5: 0.17.0
      6: 4.40.1
      8:
      - 1
      - 5
      13: linux-x86_64
